### ISSUE TITLE
Create new PyTorch Module

### ISSUE THREAD

**Issue by Jegp** [skiwan/SnnVsAnn#1]
1. Main method so it can be run with `python my_awesome_module.py`
2. Some form of `forward` method that expects input *of the correct shape*
3. Some form of fake [dataset](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html) that you inject into the model
    * Verify that the correct output arrives *from* the `forward` method

**Comment by skiwan** [comment]
Done for the binary classifier, multiclass missing

can be tested with the "test_train_binary_class.py" to show training of "odd spiking behavior" 
Current problem before we can move on to Multiclass is that the gradient during backwards pass of the linear layer (output weights) is zero, and therefore no weight adjustment happens.
